[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.162.1"
  HUGO_ENV = "production"
  # Zet op "false" als je geen extended versie gebruikt (check: "hugo version" toont "extended")
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"

[context.branch-deploy.environment]
  HUGO_ENV = "preview"

# Nette 404-pagina
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404